global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'platform'
    metrics_path: '/'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:9999' ]