version: "3.3"
services:
  node_0:
    container_name: node_0
    image: ${REGISTRY_PREFIX}services-node:${TAG}
    environment:
      - NODE_ID=0
    volumes:
      - "./../hedera-node/configuration/compose:/opt/hedera/services/config-mount"
      - "./compose-network/node0/saved:/opt/hedera/services/data/saved"
      - "./compose-network/node0/output:/opt/hedera/services/output"
    ports:
      - 50211:50211
  node_1:
    container_name: node_1
    image: ${REGISTRY_PREFIX}services-node:${TAG}
    environment:
      - NODE_ID=1
    volumes:
      - "./../hedera-node/configuration/compose:/opt/hedera/services/config-mount"
      - "./compose-network/node1/saved:/opt/hedera/services/data/saved"
      - "./compose-network/node1/output:/opt/hedera/services/output"
    ports:
      - 50212:50211
  node_2:
    container_name: node_2
    image: ${REGISTRY_PREFIX}services-node:${TAG}
    environment:
      - NODE_ID=2
    volumes:
      - "./../hedera-node/configuration/compose:/opt/hedera/services/config-mount"
      - "./compose-network/node2/saved:/opt/hedera/services/data/saved"
      - "./compose-network/node2/output:/opt/hedera/services/output"
    ports:
      - 50213:50211
