[toolchain]
channel = "stable"
components = [ "rustfmt", "rustc-dev" ]
targets = [ "x86_64-apple-darwin", "aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-gnu" ]
profile = "minimal"
