release:
  branching:
    execution:
      time: "17:00:00"
    schedule:
      - on: "2024-08-30"
        name: release/0.54
        initial-tag:
          create: true
          name: v0.54.0-alpha.1

