release:
  branching:
    execution:
      time: "17:00:00"
    schedule:
      - on: "2024-09-31"
        name: release/0.55
        initial-tag:
          create: false
          name: v0.55.0-alpha.2

