name: E2E

on:
  pull_request:
    branches: [ master, release/** ]
  push:
    branches: [ master, release/** ]
    tags: [ v* ]

jobs:
  run-e2e-tests:
    name: "Run E2E Tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        packages: ['contract.opcodes,contract.openzeppelin,contract.traceability',
                   'contract.precompile.part1,contract.records,ethereum',
                   'contract.precompile.part2,contract.hapi',
                   'contract.opcodes.eth,contract.openzeppelin.eth,contract.traceability.eth',
                   'contract.precompile.part1.eth,contract.records.eth',
                   'contract.precompile.part2.eth,contract.hapi.eth']

    steps:
      - uses: actions/checkout@v2 # checkout current branch
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build docker images # build the image for hedera-node
        run: bash compose-build.sh
      - name: Start network # start 3 node network
        run: docker compose up -d
      - name: Healthcheck for Hedera node # wait until node is ready to serve requests
        working-directory: .github/scripts
        run: bash healthcheck.sh
      - name: Run E2E Suites # run selected e2e suites
        run: ./mvnw test -pl test-clients -Dtest=E2EPackageRunner -DdefaultPort=50213 -DfailIfNoTests=false -Dpackages=${{matrix.packages}}
      - name: Upload surefire report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: surefire-report-(${{matrix.packages}})
          path: test-clients/target/surefire-reports/*

  publish-test-results:
    name: "Publish E2E Tests Results"
    needs: run-e2e-tests
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish E2E Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml
          check_name: "E2E Tests Results"
          comment_title: "E2E Tests Results"
