##
# Copyright (C) 2022-2023 Hedera Hashgraph, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

name: "Node: FSTS Daily Regression"
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The branch, tag or SHA to checkout."
        required: false
        type: string
      branch-name:
        description: ""
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  interval-01:
    name: Interval 1
    uses: ./.github/workflows/platform-zxc-launch-jrs-workflow.yaml
    with:
      ref: ${{ github.event.inputs.ref || github.sha }}
      branch-name: ${{ github.event.inputs.branch-name || github.ref_name }}
      workflow-file: node-flow-fsts-daily-interval-01.yaml
      concurrency-group: ${{ github.event.inputs.ref || github.sha }}-flow-jrs-daily-group-01
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}

  interval-02:
    name: Interval 2
    uses: ./.github/workflows/platform-zxc-launch-jrs-workflow.yaml
    needs:
      - interval-01
    with:
      ref: ${{ github.event.inputs.ref || github.sha }}
      branch-name: ${{ github.event.inputs.branch-name || github.ref_name }}
      workflow-file: node-flow-fsts-daily-interval-02.yaml
      concurrency-group: ${{ github.event.inputs.ref || github.sha }}-flow-jrs-daily-group-02
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}

  interval-03:
    name: Interval 3
    uses: ./.github/workflows/platform-zxc-launch-jrs-workflow.yaml
    needs:
      - interval-02
    with:
      ref: ${{ github.event.inputs.ref || github.sha }}
      branch-name: ${{ github.event.inputs.branch-name || github.ref_name }}
      workflow-file: node-flow-fsts-daily-interval-03.yaml
      concurrency-group: ${{ github.event.inputs.ref || github.sha }}-flow-jrs-daily-group-03
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}

  interval-04:
    name: Interval 4
    uses: ./.github/workflows/platform-zxc-launch-jrs-workflow.yaml
    needs:
      - interval-03
    with:
      ref: ${{ github.event.inputs.ref || github.sha }}
      branch-name: ${{ github.event.inputs.branch-name || github.ref_name }}
      workflow-file: node-flow-fsts-daily-interval-04.yaml
      concurrency-group: ${{ github.event.inputs.ref || github.sha }}-flow-jrs-daily-group-04
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}

  interval-05:
    name: Interval 5
    uses: ./.github/workflows/platform-zxc-launch-jrs-workflow.yaml
    needs:
      - interval-04
    with:
      ref: ${{ github.event.inputs.ref || github.sha }}
      branch-name: ${{ github.event.inputs.branch-name || github.ref_name }}
      workflow-file: node-flow-fsts-daily-interval-05.yaml
      concurrency-group: ${{ github.event.inputs.ref || github.sha }}-flow-jrs-daily-group-05
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}

  interval-06:
    name: Interval 6
    uses: ./.github/workflows/platform-zxc-launch-jrs-workflow.yaml
    needs:
      - interval-05
    with:
      ref: ${{ github.event.inputs.ref || github.sha }}
      branch-name: ${{ github.event.inputs.branch-name || github.ref_name }}
      workflow-file: node-flow-fsts-daily-interval-06.yaml
      concurrency-group: ${{ github.event.inputs.ref || github.sha }}-flow-jrs-daily-group-06
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
