##
# Copyright (C) 2022-2023 Hedera Hashgraph, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

name: "Platform: Deploy EA Release"
on:
  workflow_dispatch:
    inputs:
      version-type:
        description: "Version Type:"
        type: choice
        required: true
        options:
          - alpha
          - beta
          - rc
        default: alpha
      version-increment:
        description: "Version Increment:"
        type: choice
        required: true
        options:
          - premajor
          - preminor
          - prepatch
          - prerelease
        default: preminor
      dry-run-enabled:
        description: "Perform Dry Run"
        type: boolean
        required: false
        default: false
      java-version:
        description: "Java JDK Version:"
        type: string
        required: false
        default: "17.0.3"
      java-distribution:
        description: "Java JDK Distribution:"
        type: string
        required: false
        default: "temurin"
      gradle-version:
        description: "Gradle Version:"
        type: string
        required: false
        default: "wrapper"

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: write

jobs:
  prepare-release:
    name: "Branch / Release / Prepare"
    runs-on: [self-hosted, Linux, medium, ephemeral]
    outputs:
      version-number: ${{ steps.next-version.outputs.version }}
      version-tag: ${{ steps.next-version.outputs.version_tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Compute Next Release Version
        id: next-version
        uses: zwaldowski/semver-release-action@v3
        with:
          dry_run: true
          bump: ${{ github.event.inputs.version-increment }}
          preid: ${{ github.event.inputs.version-type }}
          prefix: "v"
          github_token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}

  ea-release:
    name: "Branch"
    uses: ./.github/workflows/platform-zxc-release-internal.yaml
    needs:
      - prepare-release
    with:
      java-version: ${{ github.event.inputs.java-version || '17.0.3' }}
      java-distribution: ${{ github.event.inputs.java-distribution || 'temurin' }}
      gradle-version: ${{ github.event.inputs.gradle-version || 'wrapper' }}
      deployment-profile: prerelease-channel
      version-policy: early-access-explicit
      new-version: ${{ needs.prepare-release.outputs.version-number }}
      custom-job-label: "Release / Early Access"
      dry-run-enabled: ${{ github.event.inputs.dry-run-enabled == 'true' }}
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
      gpg-key-contents: ${{ secrets.PLATFORM_GPG_KEY_CONTENTS }}
      gpg-key-passphrase: ${{ secrets.PLATFORM_GPG_KEY_PASSPHRASE }}
      git-user-name: ${{ secrets.PLATFORM_GIT_USER_NAME }}
      git-user-email: ${{ secrets.PLATFORM_GIT_USER_EMAIL }}

  finalize-release:
    name: "Branch / Release / Finalize"
    runs-on: [self-hosted, Linux, medium, ephemeral]
    needs:
      - prepare-release
      - ea-release
    if: ${{ github.event.inputs.dry-run-enabled != 'true' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Compute Commit Identifier
        id: commit
        run: |
          echo "id=$(git rev-parse HEAD | tr -d '[:space:]')" >> "${GITHUB_OUTPUT}"
          echo "short-id=$(git rev-parse HEAD | tr -d '[:space:]' | cut -c1-8)" >> "${GITHUB_OUTPUT}"

      - name: Compute Next Release Version
        id: next-version
        uses: zwaldowski/semver-release-action@v3
        with:
          dry_run: false
          bump: ${{ github.event.inputs.version-increment }}
          preid: ${{ github.event.inputs.version-type }}
          prefix: "v"
          sha: ${{ steps.commit.outputs.id }}
          github_token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}

      - name: Publish Github Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          generate_release_notes: true
          prerelease: true
          name: Platform SDK Release ${{ steps.next-version.outputs.version_tag }}
          tag_name: ${{ steps.next-version.outputs.version_tag }}
          token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ secrets.PLATFORM_SLACK_RELEASE_WEBHOOK }}
        with:
          payload: |
            {
              "attachments": [
                  {
                    "color": "#b7f350",
                    "blocks": [
                      {
                        "type": "header",
                        "text": {
                          "type": "plain_text",
                          "text": ":dvd: Platform SDK Release ${{ steps.next-version.outputs.version_tag }}",
                          "emoji": true
                        }
                      },
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Deployment Channel:*"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Deployment Status Check:*"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "Internal Prerelease"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "Not Applicable"
                          }
                        ]
                      },
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Source Branch:*"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Short Commit ID:*"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "`${{ steps.commit.outputs.short-id }}`"
                          }
                        ]
                      },
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Maven Version Number:*"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Release Notes:*"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "`${{ steps.next-version.outputs.version }}`"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "<${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ steps.next-version.outputs.version_tag }}|${{ steps.next-version.outputs.version_tag }}>"
                          }
                        ]
                      },
                      {
                        "type": "divider"
                      },
                      {
                        "type": "context",
                        "elements": [
                          {
                            "type": "mrkdwn",
                            "text": ":outbox_tray: @Neeha @michael.tinker @simi @Richard"
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
