##
# Copyright (C) 2022-2023 Hedera Hashgraph, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

name: "Platform: Deploy MC Release"
on:
  workflow_dispatch:
    inputs:
      dry-run-enabled:
        description: "Perform Dry Run"
        type: boolean
        required: false
        default: false
      new-version:
        description: "New Release Version (ie. 0.30.0):"
        type: string
        required: true
      java-version:
        description: "Java JDK Version:"
        type: string
        required: false
        default: "17.0.3"
      java-distribution:
        description: "Java JDK Distribution:"
        type: string
        required: false
        default: "temurin"

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: write

jobs:
  prepare-release:
    name: "Branch / Release / Prepare"
    runs-on: [self-hosted, Linux, medium, ephemeral]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check for Tag Existence
        id: tag
        uses: mukunku/tag-exists-action@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
        with:
          tag: v${{ github.event.inputs.new-version }}

      - name: Fail on Duplicate Tag
        run: |
          if [[ "${{ steps.tag.outputs.exists }}" == true ]]; then
            echo "::error title=Duplicate Tag Error::The supplied new-version parameter (${{ github.event.inputs.new-version }}) would result in a duplicate tag (v${{ github.event.inputs.new-version }})."
            exit 1
          fi

  mc-release:
    name: "Branch"
    uses: ./.github/workflows/platform-zxc-release-maven-central.yaml
    needs:
      - prepare-release
    with:
      new-version: ${{ github.event.inputs.new-version }}
      dry-run-enabled: ${{ github.event.inputs.dry-run-enabled == 'true' }}
      java-distribution: ${{ github.event.inputs.java-distribution || 'temurin' }}
      java-version: ${{ github.event.inputs.java-version || '17.0.3' }}
      custom-job-label: "Release / Maven Central"
    secrets:
      gpg-key-contents: ${{ secrets.PLATFORM_GPG_KEY_CONTENTS }}
      gpg-key-passphrase: ${{ secrets.PLATFORM_GPG_KEY_PASSPHRASE }}
      git-user-name: ${{ secrets.PLATFORM_GIT_USER_NAME }}
      git-user-email: ${{ secrets.PLATFORM_GIT_USER_EMAIL }}
      ossrh-user-name: ${{ secrets.PLATFORM_OSSRH_USERNAME }}
      ossrh-user-password: ${{ secrets.PLATFORM_OSSRH_PASSWORD }}

  finalize-release:
    name: "Branch / Release / Finalize"
    runs-on: [self-hosted, Linux, medium, ephemeral]
    needs:
      - prepare-release
      - mc-release
    if: ${{ github.event.inputs.dry-run-enabled != 'true' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Compute Commit Identifier
        id: commit
        run: |
          echo "id=$(git rev-parse HEAD | tr -d '[:space:]')" >> "${GITHUB_OUTPUT}"
          echo "short-id=$(git rev-parse HEAD | tr -d '[:space:]' | cut -c1-8)" >> "${GITHUB_OUTPUT}"

      - name: Cache SDK Release Archives
        id: archive-cache
        uses: actions/cache@v3
        with:
          path: ~/sdk-archives
          key: v1-sdk-release-v${{ github.event.inputs.new-version }}-jdk${{ github.event.inputs.java-version }}-${{ runner.os }}-${{ runner.arch }}-ri${{ github.run_id }}-rn${{ github.run_number }}-ra${{ github.run_attempt }}

      - name: Verify SDK Release Archive
        id: sdk-archives
        run: |
          if [[ "${{ steps.archive-cache.outputs.cache-hit }}" != true ]]; then
            echo "::error title=SDK Release Error::Unable to locate the SDK Release artifacts in the cache."
            exit 1
          fi

          echo "path=${HOME}/sdk-archives" >> "${GITHUB_OUTPUT}"

      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        with:
          github_token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
          commit_sha: ${{ steps.commit.outputs.id }}
          message: "[Automated Maven Central Release] Platform SDK Release v${{ github.event.inputs.new-version }}"
          tag: v${{ github.event.inputs.new-version }}

      - name: Publish Github Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          generate_release_notes: true
          prerelease: false
          name: Platform SDK Release v${{ github.event.inputs.new-version }}
          tag_name: v${{ github.event.inputs.new-version }}
          token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
          files: ${{ steps.sdk-archives.outputs.path }}/*

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ secrets.PLATFORM_SLACK_RELEASE_WEBHOOK }}
        with:
          payload: |
            {
              "attachments": [
                  {
                    "color": "#b7f350",
                    "blocks": [
                      {
                        "type": "header",
                        "text": {
                          "type": "plain_text",
                          "text": ":dvd: Platform SDK Release v${{ github.event.inputs.new-version }}",
                          "emoji": true
                        }
                      },
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Deployment Channel:*"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Deployment Status Check:*"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "Maven Central"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "<https://repo1.maven.org/maven2/com/swirlds/swirlds-platform-core/${{ github.event.inputs.new-version }}/|MC Availability Check>"
                          }
                        ]
                      },
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Source Branch:*"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Short Commit ID:*"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "`${{ steps.commit.outputs.short-id }}`"
                          }
                        ]
                      },
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Gradle Version Number:*"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Release Notes:*"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "`${{ github.event.inputs.new-version }}`"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "<${{ github.server_url }}/${{ github.repository }}/releases/tag/v${{ github.event.inputs.new-version }}|v${{ github.event.inputs.new-version }}>"
                          }
                        ]
                      },
                      {
                        "type": "divider"
                      },
                      {
                        "type": "context",
                        "elements": [
                          {
                            "type": "mrkdwn",
                            "text": ":outbox_tray: @Neeha @michael.tinker @simi @Richard"
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
